name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: GIT_BRANCH_NAME= echo ${GITHUB_REF##*/} >> $GITHUB_ENV && echo "$GIT_BRANCH_NAME" #echo "GIT_BRANCH_NAME=`echo ${GITHUB_REF##*/}`" >> $GITHUB_ENV && echo "$GIT_BRANCH_NAME"

