name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      - name: Add GITHUB_WORKFLOW_LABEL env property with run number and commit short sha
        run: echo "GITHUB_WORKFLOW_LABEL=${{ github.run_number }}-`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      - run: echo "${{ github.run_number }}-$(echo "${{ github.sha }}" | cut -c1-7)"


